# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.new(username:"prueba1",password:"contrasena1")

Solicitud.new(
    {PrimerNombre: "Prueba_Solicitudes_14",
      PrimerApellido: "Prueba_14",
      Estado: 0,
      Genero: "M",
      TipoDocumento: "cc",
      cc: 1231231,
      cellphone: 1231231,
      cellphone2: 1231231,
      Whatsapp: "Si",
      CorreoElectronico: "correo@arroba.punto",
      MunicipioRes: "Medellin",
      DepartamentoRes: "Antioquia",
      DireccionRes: "al lado de ahí",
      Vereda: "N/A",
      TipoVivienda: "Propia",
      ResidenciaYears: 2,
      NivelEstudios: "Profesional",
      PersonasCargo: "5",
      ViveDondeTrabaja: "Si",
      MunicipioTrabajo: "Medellin",
      DepartamentoTrabajo: "Antioquia",
      IngresoPpl: "Salario",
      OtrosIngresos: "NA",
      ProduccionPpl: "Agrícola",
      Producto1: "Café",
      Producto1Diferente: "N/A",
      ProduccionSec: "Pecuaria",
      Producto2: "N/A",
      Producto2Diferente:"otro",
      ExperienciaSectorAgropecuario: 3,
      ExperienciaActividad: 2,
      HectareasProductivas: 10,
      Tenencia: "Propia",
      ViaAcceso: "Si",
      IngresoMensual: 4,
      CostoActividad: 5,
      TipoSol: "Vinculacion",
      TipoSolicitante: "Codeudor",
      Productosolicitado: "CrediTiendas",
      MontoSolicitado: 2,
      Objetivo: "MaquinariaEquipo",
      GastosFamiliares: 123123,
      Plazo: 1,
      Garantia: "Si",
      FuentePago: "Si",
      
      reason: "Inversion",
      uid: "518otvIV5bhtfMryZx79",
      applicationsLoan:TRUE,
      es_conocido_en_tiendas: "si",
      farmerphotos: '',
      store: 'id=>XjXQcXYswNNvEBoXsNCck6CWVuu1,email=>correo@correo.com,name=>Sebastian,role=>TIENDA',
      uniqueNumberApplicationLoan: 3333,
      comments: '',
      comercial_obj: 'dummy_var=>val,prueba=>1',
      analisis_obj: '',
      referenciacion_obj: '',
      desembolso_obj: '',
      tesoreria_obj: '',
                 
      familiar_reference_1: 'Nombre=>x, Parentesco=>y, Telefono=>1231231',
      familiar_reference_2: 'Nombre=>x, Parentesco=>y, Telefono=>1231231',
      personal_reference_1: 'Nombre=>x, QuienEs=>y, Telefono=>1231231'})